version: "3.7"
services:
  postgres:
    image: postgres:16.1
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]

  zlagoda_frontend:
    depends_on:
      - openapi_generator
      - zlagoda_backend
    build:
      context: ./web_src/zlagoda
    ports:
      - "3000:3000"
    volumes:
      - ./web_src/zlagoda:/app
      - /app/node_modules
    env_file:
      - .env

  zlagoda_backend:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./src
    volumes:
      - ./src:/app
    ports:
      - "3333:3333"
    command: sh -c "yoyo apply && uvicorn src.main:app --host 0.0.0.0 --port 3333"
    env_file:
      - .env

  openapi_generator:
    build:
      context: ./openapi_generator
    volumes:
      - ./src/api:/in/api:ro
      - ./src:/out/src
      - ./web_src/zlagoda/generated:/out/web_src/generated
