version: "3.7"
services:
  postgres:
    image: postgres:16.1
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}

  zlagoda_frontend:
    depends_on:
      - openapi_generator
    build:
      context: ./web_src/zlagoda
    ports:
      - "3000:3000"
    volumes:
      - ./web_src/zlagoda:/app
      - /app/node_modules
    env_file:
      - .env

  zlagoda_backend:
    depends_on:
      - openapi_generator
      - postgres
    build:
      context: ./src
    ports:
      - "3333:3333"
    command: yoyo apply ; uvicorn openapi_server.main:app --host 0.0.0.0 --port 3333
    env_file:
      - .env

  openapi_generator:
    build:
      context: ./openapi_generator
    volumes:
      - ./src/api:/in/api:ro
      - ./src:/out/src
      - ./web_src/zlagoda/generated:/out/web_src/generated
