# coding: utf-8

"""
    Zlagoda

    API for systems used by the employees of Zlagoda shops

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.customer_card_api import router as CustomerCardApiRouter
from openapi_server.apis.employee_api import router as EmployeeApiRouter
from openapi_server.apis.product_api import router as ProductApiRouter
from openapi_server.apis.product_archetype_api import router as ProductArchetypeApiRouter
from openapi_server.apis.product_category_api import router as ProductCategoryApiRouter
from openapi_server.apis.receipt_api import router as ReceiptApiRouter

app = FastAPI(
    title="Zlagoda",
    description="API for systems used by the employees of Zlagoda shops",
    version="1.0.0",
)

app.include_router(CustomerCardApiRouter)
app.include_router(EmployeeApiRouter)
app.include_router(ProductApiRouter)
app.include_router(ProductArchetypeApiRouter)
app.include_router(ProductCategoryApiRouter)
app.include_router(ReceiptApiRouter)
