from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.employee_role import EmployeeRole
from openapi_server import util

from openapi_server.models.employee_role import EmployeeRole  # noqa: E501

class Employee(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name=None, last_name=None, patronymic=None, role=None, salary=None, work_start_date=None, birth_date=None, phone_number=None, city=None, street=None, zip_code=None, id=None):  # noqa: E501
        """Employee - a model defined in OpenAPI

        :param first_name: The first_name of this Employee.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Employee.  # noqa: E501
        :type last_name: str
        :param patronymic: The patronymic of this Employee.  # noqa: E501
        :type patronymic: str
        :param role: The role of this Employee.  # noqa: E501
        :type role: EmployeeRole
        :param salary: The salary of this Employee.  # noqa: E501
        :type salary: int
        :param work_start_date: The work_start_date of this Employee.  # noqa: E501
        :type work_start_date: date
        :param birth_date: The birth_date of this Employee.  # noqa: E501
        :type birth_date: date
        :param phone_number: The phone_number of this Employee.  # noqa: E501
        :type phone_number: str
        :param city: The city of this Employee.  # noqa: E501
        :type city: str
        :param street: The street of this Employee.  # noqa: E501
        :type street: str
        :param zip_code: The zip_code of this Employee.  # noqa: E501
        :type zip_code: str
        :param id: The id of this Employee.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'patronymic': str,
            'role': EmployeeRole,
            'salary': int,
            'work_start_date': date,
            'birth_date': date,
            'phone_number': str,
            'city': str,
            'street': str,
            'zip_code': str,
            'id': int
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'patronymic': 'patronymic',
            'role': 'role',
            'salary': 'salary',
            'work_start_date': 'workStartDate',
            'birth_date': 'birthDate',
            'phone_number': 'phoneNumber',
            'city': 'city',
            'street': 'street',
            'zip_code': 'zipCode',
            'id': 'id'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._patronymic = patronymic
        self._role = role
        self._salary = salary
        self._work_start_date = work_start_date
        self._birth_date = birth_date
        self._phone_number = phone_number
        self._city = city
        self._street = street
        self._zip_code = zip_code
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Employee':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Employee of this Employee.  # noqa: E501
        :rtype: Employee
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Employee.


        :return: The first_name of this Employee.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Employee.


        :param first_name: The first_name of this Employee.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Employee.


        :return: The last_name of this Employee.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Employee.


        :param last_name: The last_name of this Employee.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def patronymic(self) -> str:
        """Gets the patronymic of this Employee.


        :return: The patronymic of this Employee.
        :rtype: str
        """
        return self._patronymic

    @patronymic.setter
    def patronymic(self, patronymic: str):
        """Sets the patronymic of this Employee.


        :param patronymic: The patronymic of this Employee.
        :type patronymic: str
        """

        self._patronymic = patronymic

    @property
    def role(self) -> EmployeeRole:
        """Gets the role of this Employee.


        :return: The role of this Employee.
        :rtype: EmployeeRole
        """
        return self._role

    @role.setter
    def role(self, role: EmployeeRole):
        """Sets the role of this Employee.


        :param role: The role of this Employee.
        :type role: EmployeeRole
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def salary(self) -> int:
        """Gets the salary of this Employee.


        :return: The salary of this Employee.
        :rtype: int
        """
        return self._salary

    @salary.setter
    def salary(self, salary: int):
        """Sets the salary of this Employee.


        :param salary: The salary of this Employee.
        :type salary: int
        """
        if salary is None:
            raise ValueError("Invalid value for `salary`, must not be `None`")  # noqa: E501

        self._salary = salary

    @property
    def work_start_date(self) -> date:
        """Gets the work_start_date of this Employee.


        :return: The work_start_date of this Employee.
        :rtype: date
        """
        return self._work_start_date

    @work_start_date.setter
    def work_start_date(self, work_start_date: date):
        """Sets the work_start_date of this Employee.


        :param work_start_date: The work_start_date of this Employee.
        :type work_start_date: date
        """
        if work_start_date is None:
            raise ValueError("Invalid value for `work_start_date`, must not be `None`")  # noqa: E501

        self._work_start_date = work_start_date

    @property
    def birth_date(self) -> date:
        """Gets the birth_date of this Employee.


        :return: The birth_date of this Employee.
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date: date):
        """Sets the birth_date of this Employee.


        :param birth_date: The birth_date of this Employee.
        :type birth_date: date
        """
        if birth_date is None:
            raise ValueError("Invalid value for `birth_date`, must not be `None`")  # noqa: E501

        self._birth_date = birth_date

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this Employee.


        :return: The phone_number of this Employee.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this Employee.


        :param phone_number: The phone_number of this Employee.
        :type phone_number: str
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def city(self) -> str:
        """Gets the city of this Employee.


        :return: The city of this Employee.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Employee.


        :param city: The city of this Employee.
        :type city: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def street(self) -> str:
        """Gets the street of this Employee.


        :return: The street of this Employee.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this Employee.


        :param street: The street of this Employee.
        :type street: str
        """
        if street is None:
            raise ValueError("Invalid value for `street`, must not be `None`")  # noqa: E501

        self._street = street

    @property
    def zip_code(self) -> str:
        """Gets the zip_code of this Employee.


        :return: The zip_code of this Employee.
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: str):
        """Sets the zip_code of this Employee.


        :param zip_code: The zip_code of this Employee.
        :type zip_code: str
        """
        if zip_code is None:
            raise ValueError("Invalid value for `zip_code`, must not be `None`")  # noqa: E501

        self._zip_code = zip_code

    @property
    def id(self) -> int:
        """Gets the id of this Employee.


        :return: The id of this Employee.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Employee.


        :param id: The id of this Employee.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
