from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.employee_role import EmployeeRole
from openapi_server import util

from openapi_server.models.employee_role import EmployeeRole  # noqa: E501

class EmployeeCriteria(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=None, limit=None, sort_field=None, sort_ascending=None, role=None, last_name=None):  # noqa: E501
        """EmployeeCriteria - a model defined in OpenAPI

        :param offset: The offset of this EmployeeCriteria.  # noqa: E501
        :type offset: int
        :param limit: The limit of this EmployeeCriteria.  # noqa: E501
        :type limit: int
        :param sort_field: The sort_field of this EmployeeCriteria.  # noqa: E501
        :type sort_field: str
        :param sort_ascending: The sort_ascending of this EmployeeCriteria.  # noqa: E501
        :type sort_ascending: bool
        :param role: The role of this EmployeeCriteria.  # noqa: E501
        :type role: EmployeeRole
        :param last_name: The last_name of this EmployeeCriteria.  # noqa: E501
        :type last_name: str
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'sort_field': str,
            'sort_ascending': bool,
            'role': EmployeeRole,
            'last_name': str
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'sort_field': 'sortField',
            'sort_ascending': 'sortAscending',
            'role': 'role',
            'last_name': 'lastName'
        }

        self._offset = offset
        self._limit = limit
        self._sort_field = sort_field
        self._sort_ascending = sort_ascending
        self._role = role
        self._last_name = last_name

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeCriteria':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeCriteria of this EmployeeCriteria.  # noqa: E501
        :rtype: EmployeeCriteria
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self) -> int:
        """Gets the offset of this EmployeeCriteria.


        :return: The offset of this EmployeeCriteria.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this EmployeeCriteria.


        :param offset: The offset of this EmployeeCriteria.
        :type offset: int
        """

        self._offset = offset

    @property
    def limit(self) -> int:
        """Gets the limit of this EmployeeCriteria.


        :return: The limit of this EmployeeCriteria.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this EmployeeCriteria.


        :param limit: The limit of this EmployeeCriteria.
        :type limit: int
        """

        self._limit = limit

    @property
    def sort_field(self) -> str:
        """Gets the sort_field of this EmployeeCriteria.


        :return: The sort_field of this EmployeeCriteria.
        :rtype: str
        """
        return self._sort_field

    @sort_field.setter
    def sort_field(self, sort_field: str):
        """Sets the sort_field of this EmployeeCriteria.


        :param sort_field: The sort_field of this EmployeeCriteria.
        :type sort_field: str
        """

        self._sort_field = sort_field

    @property
    def sort_ascending(self) -> bool:
        """Gets the sort_ascending of this EmployeeCriteria.


        :return: The sort_ascending of this EmployeeCriteria.
        :rtype: bool
        """
        return self._sort_ascending

    @sort_ascending.setter
    def sort_ascending(self, sort_ascending: bool):
        """Sets the sort_ascending of this EmployeeCriteria.


        :param sort_ascending: The sort_ascending of this EmployeeCriteria.
        :type sort_ascending: bool
        """

        self._sort_ascending = sort_ascending

    @property
    def role(self) -> EmployeeRole:
        """Gets the role of this EmployeeCriteria.


        :return: The role of this EmployeeCriteria.
        :rtype: EmployeeRole
        """
        return self._role

    @role.setter
    def role(self, role: EmployeeRole):
        """Sets the role of this EmployeeCriteria.


        :param role: The role of this EmployeeCriteria.
        :type role: EmployeeRole
        """

        self._role = role

    @property
    def last_name(self) -> str:
        """Gets the last_name of this EmployeeCriteria.


        :return: The last_name of this EmployeeCriteria.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this EmployeeCriteria.


        :param last_name: The last_name of this EmployeeCriteria.
        :type last_name: str
        """

        self._last_name = last_name
