from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductCategory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None):  # noqa: E501
        """ProductCategory - a model defined in OpenAPI

        :param name: The name of this ProductCategory.  # noqa: E501
        :type name: str
        :param id: The id of this ProductCategory.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'name': str,
            'id': int
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id'
        }

        self._name = name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'ProductCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductCategory of this ProductCategory.  # noqa: E501
        :rtype: ProductCategory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProductCategory.


        :return: The name of this ProductCategory.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductCategory.


        :param name: The name of this ProductCategory.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def id(self) -> int:
        """Gets the id of this ProductCategory.


        :return: The id of this ProductCategory.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProductCategory.


        :param id: The id of this ProductCategory.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
