from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductView(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, archetype=None, upc=None, price=None, quantity=None):  # noqa: E501
        """ProductView - a model defined in OpenAPI

        :param archetype: The archetype of this ProductView.  # noqa: E501
        :type archetype: int
        :param upc: The upc of this ProductView.  # noqa: E501
        :type upc: str
        :param price: The price of this ProductView.  # noqa: E501
        :type price: int
        :param quantity: The quantity of this ProductView.  # noqa: E501
        :type quantity: int
        """
        self.openapi_types = {
            'archetype': int,
            'upc': str,
            'price': int,
            'quantity': int
        }

        self.attribute_map = {
            'archetype': 'archetype',
            'upc': 'upc',
            'price': 'price',
            'quantity': 'quantity'
        }

        self._archetype = archetype
        self._upc = upc
        self._price = price
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ProductView':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductView of this ProductView.  # noqa: E501
        :rtype: ProductView
        """
        return util.deserialize_model(dikt, cls)

    @property
    def archetype(self) -> int:
        """Gets the archetype of this ProductView.


        :return: The archetype of this ProductView.
        :rtype: int
        """
        return self._archetype

    @archetype.setter
    def archetype(self, archetype: int):
        """Sets the archetype of this ProductView.


        :param archetype: The archetype of this ProductView.
        :type archetype: int
        """
        if archetype is None:
            raise ValueError("Invalid value for `archetype`, must not be `None`")  # noqa: E501

        self._archetype = archetype

    @property
    def upc(self) -> str:
        """Gets the upc of this ProductView.


        :return: The upc of this ProductView.
        :rtype: str
        """
        return self._upc

    @upc.setter
    def upc(self, upc: str):
        """Sets the upc of this ProductView.


        :param upc: The upc of this ProductView.
        :type upc: str
        """
        if upc is None:
            raise ValueError("Invalid value for `upc`, must not be `None`")  # noqa: E501

        self._upc = upc

    @property
    def price(self) -> int:
        """Gets the price of this ProductView.


        :return: The price of this ProductView.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price: int):
        """Sets the price of this ProductView.


        :param price: The price of this ProductView.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def quantity(self) -> int:
        """Gets the quantity of this ProductView.


        :return: The quantity of this ProductView.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this ProductView.


        :param quantity: The quantity of this ProductView.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
