from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SortCriteria(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sort_field=None, sort_ascending=None):  # noqa: E501
        """SortCriteria - a model defined in OpenAPI

        :param sort_field: The sort_field of this SortCriteria.  # noqa: E501
        :type sort_field: str
        :param sort_ascending: The sort_ascending of this SortCriteria.  # noqa: E501
        :type sort_ascending: bool
        """
        self.openapi_types = {
            'sort_field': str,
            'sort_ascending': bool
        }

        self.attribute_map = {
            'sort_field': 'sortField',
            'sort_ascending': 'sortAscending'
        }

        self._sort_field = sort_field
        self._sort_ascending = sort_ascending

    @classmethod
    def from_dict(cls, dikt) -> 'SortCriteria':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SortCriteria of this SortCriteria.  # noqa: E501
        :rtype: SortCriteria
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sort_field(self) -> str:
        """Gets the sort_field of this SortCriteria.


        :return: The sort_field of this SortCriteria.
        :rtype: str
        """
        return self._sort_field

    @sort_field.setter
    def sort_field(self, sort_field: str):
        """Sets the sort_field of this SortCriteria.


        :param sort_field: The sort_field of this SortCriteria.
        :type sort_field: str
        """

        self._sort_field = sort_field

    @property
    def sort_ascending(self) -> bool:
        """Gets the sort_ascending of this SortCriteria.


        :return: The sort_ascending of this SortCriteria.
        :rtype: bool
        """
        return self._sort_ascending

    @sort_ascending.setter
    def sort_ascending(self, sort_ascending: bool):
        """Sets the sort_ascending of this SortCriteria.


        :param sort_ascending: The sort_ascending of this SortCriteria.
        :type sort_ascending: bool
        """

        self._sort_ascending = sort_ascending
