openapi: 3.0.3
info:
  title: Test
  description: Test
  version: 1.0.0
servers:
  - url: https://localhost:3333
paths:
  /test:
    get:
      description: Returns test value
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: integer

components:
  schemas:
    EmployeeView:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        patronymic:
          type: string
        role:
          type: string
        salary:
          type: integer
        workStartDate:
          type: string
          format: date
        birthDate:
          type: string
          format: date
        phoneNumber:
          type: string
        city:
          type: string
        street:
          type: string
        zipCode:
          type: string
      required:
        - firstName
        - lastName
        - role
        - salary
        - workStartDate
        - birthDate
        - phoneNumber
        - city
        - street
        - zipCode

    Employee:
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/EmployeeView'

    ProductCategoryView:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    ProductCategory:
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/ProductCategoryView'

    ProductArchetypeView:
      type: object
      properties:
        name:
          type: string
        category:
          type: integer
        manufacturer:
          type: string
        description:
          type: string
      required:
        - name
        - category
        - manufacturer
        - description

    ProductArchetype:
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/ProductArchetypeView'

    ProductView:
      type: object
      properties:
        archetype:
          type: integer
        upc:
          type: string
        price:
          type: integer
        quantity:
          type: integer
      required:
        - archetype
        - upc
        - price
        - quantity

    Product:
      allOf:
        - type: object
          properties:
            id:
              type: integer
            hasDiscount:
              type: boolean
          required:
            - id
            - hasDiscount
        - $ref: '#/components/schemas/ProductView'

    ReceiptItem:
      type: object
      properties:
        productArchetype:
          type: integer
        quantity:
          type: integer
        price:
          type: integer
      required:
        - productArchetype
        - quantity
        - price

    ReceiptView:
      type: object
      properties:
        customerCardId:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReceiptItem'
      required:
        - items

    Receipt:
      type: object
      properties:
        id:
          type: integer
        cashierId:
          type: integer
        customerCardId:
          type: integer
        dateTime:
          type: string
          format: date-time
        totalPrice:
          type: integer
        vat:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReceiptItem'
      required:
        - id
        - cashierId
        - dateTime
        - totalPrice
        - vat
        - items

    CustomerCardView:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        patronymic:
          type: string
        phoneNumber:
          type: string
        discountPercent:
          type: integer
        city:
          type: string
        street:
          type: string
        zipCode:
          type: string
      required:
        - firstName
        - lastName
        - phoneNumber
        - discountPercent

    CustomerCard:
      allOf:
        - type: object
          properties:
            id:
              type: integer
          required:
            - id
        - $ref: '#/components/schemas/CustomerCardView'

    EmployeeCriteria:
      type: object
      properties:
        role:
          type: string
        lastName:
          type: string

    ProductCriteria:
      type: object
      properties:
        categoryIds:
          type: array
          items:
            type: integer
        upc:
          type: string
        name:
          type: string
        hasDiscount:
          type: boolean

    ReceiptCriteria:
      type: object
      properties:
        cashierIds:
          type: array
          items:
            type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    CustomerCardCriteria:
      type: object
      properties:
        lastName:
          type: string

    SortCriteria:
      type: object
      properties:
        sortField:
          type: string
        sortAscending:
          type: boolean
