openapi: 3.0.3
info:
  title: Test
  description: Test
  version: 1.0.0
servers:
  - url: https://localhost:3333
paths:
  /test:
    get:
      description: Returns test value
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: integer
